/**
 * Registrations Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { RegistrationCreate } from '../model/models';
import { RegistrationOut } from '../model/models';
import { RegistrationStats } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RegistrationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Annuler une inscription
     * 
     * @endpoint delete /api/registrations/{registration_id}
     * @param registrationId 
     */
    cancelRegistration(registrationId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Inscrire un participant à un événement
     * Inscription en quatre temps, dans cet ordre précis.  1. Refus si déjà inscrit — contrôle local, aucun appel réseau inutile. 2. Le participant existe-t-il ? (participants-service) 3. Réservation ATOMIQUE d\&#39;une place (events-service). 4. Enregistrement local ; si l\&#39;écriture échoue, on rend la place.
     * @endpoint post /api/registrations
     * @param registrationCreate 
     */
    createRegistration(registrationCreate: RegistrationCreate, extraHttpRequestParams?: any): Observable<RegistrationOut>;

    /**
     * Lister les inscriptions d\&#39;un événement
     * 
     * @endpoint get /api/registrations/event/{event_id}
     * @param eventId 
     */
    listByEvent(eventId: number, extraHttpRequestParams?: any): Observable<Array<RegistrationOut>>;

    /**
     * Lister les événements d\&#39;un participant
     * 
     * @endpoint get /api/registrations/participant/{participant_id}
     * @param participantId 
     */
    listByParticipant(participantId: number, extraHttpRequestParams?: any): Observable<Array<RegistrationOut>>;

    /**
     * Statistiques d\&#39;inscription
     * 
     * @endpoint get /api/registrations/stats
     */
    registrationStats(extraHttpRequestParams?: any): Observable<RegistrationStats>;

}
