/**
 * Registrations Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationOut { 
    event_id: number;
    participant_id: number;
    id: number;
    status: string;
    created_at?: string | null;
    updated_at?: string | null;
}

