/**
 * Events Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AvailabilityOut { 
    event_id: number;
    capacity: number;
    seats_taken: number;
    seats_available: number;
    is_full: boolean;
}

