/**
 * Events Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventUpdate { 
    title?: string | null;
    description?: string | null;
    starts_at?: string | null;
    location?: string | null;
    capacity?: number | null;
}

