/**
 * Events Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventOut { 
    title: string;
    description?: string | null;
    starts_at: string;
    location: string;
    capacity: number;
    id: number;
    seats_taken: number;
    created_at?: string | null;
    updated_at?: string | null;
}

