/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantOut { 
    id: number;
    full_name: string;
    email: string;
    phone?: string | null;
    type: string;
    created_at?: string | null;
    updated_at?: string | null;
}

