/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantType } from './participantType';


export interface ParticipantCreate { 
    full_name: string;
    email: string;
    phone?: string | null;
    type: ParticipantType;
}
export namespace ParticipantCreate {
}


