/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantType } from './participantType';


export interface ParticipantUpdate { 
    full_name?: string | null;
    email?: string | null;
    phone?: string | null;
    type?: ParticipantType | null;
}
export namespace ParticipantUpdate {
}


