/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Les trois types imposés par l\'énoncé.
 */
export const ParticipantType = {
    Etudiant: 'etudiant',
    Professeur: 'professeur',
    Externe: 'externe'
} as const;
export type ParticipantType = typeof ParticipantType[keyof typeof ParticipantType];

