/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Health
     * Liveness : le processus répond. Utilisé par le HEALTHCHECK Docker.
     * @endpoint get /health
     */
    health(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Readiness
     * Readiness : le service ET sa base de données répondent.
     * @endpoint get /health/ready
     */
    readiness(extraHttpRequestParams?: any): Observable<any>;

}
