/**
 * Participants Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { ParticipantCreate } from '../model/models';
import { ParticipantOut } from '../model/models';
import { ParticipantUpdate } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ParticipantsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Créer un compte participant
     * 
     * @endpoint post /api/participants
     * @param participantCreate 
     */
    createParticipant(participantCreate: ParticipantCreate, extraHttpRequestParams?: any): Observable<ParticipantOut>;

    /**
     * Supprimer un participant
     * 
     * @endpoint delete /api/participants/{participant_id}
     * @param participantId 
     */
    deleteParticipant(participantId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Détail d\&#39;un participant
     * 
     * @endpoint get /api/participants/{participant_id}
     * @param participantId 
     */
    getParticipant(participantId: number, extraHttpRequestParams?: any): Observable<ParticipantOut>;

    /**
     * Lister les participants
     * Liste les participants. &#x60;search&#x60; filtre sur le nom OU l\&#39;email.
     * @endpoint get /api/participants
     * @param search 
     */
    listParticipants(search?: string, extraHttpRequestParams?: any): Observable<Array<ParticipantOut>>;

    /**
     * Modifier un profil participant
     * 
     * @endpoint put /api/participants/{participant_id}
     * @param participantId 
     * @param participantUpdate 
     */
    updateParticipant(participantId: number, participantUpdate: ParticipantUpdate, extraHttpRequestParams?: any): Observable<ParticipantOut>;

}
