/**
 * Events Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AvailabilityOut } from '../model/models';
import { EventCreate } from '../model/models';
import { EventOut } from '../model/models';
import { EventUpdate } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Places restantes
     * 
     * @endpoint get /api/events/{event_id}/availability
     * @param eventId 
     */
    availability(eventId: number, extraHttpRequestParams?: any): Observable<AvailabilityOut>;

    /**
     * Créer un événement
     * 
     * @endpoint post /api/events
     * @param eventCreate 
     */
    createEvent(eventCreate: EventCreate, extraHttpRequestParams?: any): Observable<EventOut>;

    /**
     * Supprimer un événement
     * 
     * @endpoint delete /api/events/{event_id}
     * @param eventId 
     */
    deleteEvent(eventId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Détail d\&#39;un événement
     * 
     * @endpoint get /api/events/{event_id}
     * @param eventId 
     */
    getEvent(eventId: number, extraHttpRequestParams?: any): Observable<EventOut>;

    /**
     * Lister les événements
     * Liste les événements, avec filtres optionnels par date et par lieu.
     * @endpoint get /api/events
     * @param date 
     * @param location 
     */
    listEvents(date?: string, location?: string, extraHttpRequestParams?: any): Observable<Array<EventOut>>;

    /**
     * [interne] Libérer une place
     * 
     * @endpoint post /api/events/{event_id}/seats/release
     * @param eventId 
     */
    releaseSeat(eventId: number, extraHttpRequestParams?: any): Observable<AvailabilityOut>;

    /**
     * [interne] Réserver une place
     * 
     * @endpoint post /api/events/{event_id}/seats/reserve
     * @param eventId 
     */
    reserveSeat(eventId: number, extraHttpRequestParams?: any): Observable<AvailabilityOut>;

    /**
     * Modifier un événement
     * 
     * @endpoint put /api/events/{event_id}
     * @param eventId 
     * @param eventUpdate 
     */
    updateEvent(eventId: number, eventUpdate: EventUpdate, extraHttpRequestParams?: any): Observable<EventOut>;

}
